# Generated by Django 4.2.3 on 2023-08-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_equipments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.TextField()),
                ('task_id', models.TextField()),
                ('equipment_id', models.TextField()),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('onprogress', models.CharField(default='True', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskPerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.TextField()),
                ('location_id', models.TextField()),
                ('task_id', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('onprogress', models.CharField(default='True', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('location_id', models.TextField()),
                ('task_id', models.TextField()),
                ('days', models.IntegerField(default=0)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('onprogress', models.CharField(default='True', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='locations',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.TextField(),
        ),
    ]
