# Generated by Django 4.2.3 on 2023-08-03 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_requirements_taskperproject_workers_locations_budget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipments',
            old_name='description',
            new_name='equipment_description',
        ),
        migrations.RenameField(
            model_name='equipments',
            old_name='name',
            new_name='equipment_name',
        ),
        migrations.RenameField(
            model_name='locations',
            old_name='description',
            new_name='location_description',
        ),
        migrations.RenameField(
            model_name='locations',
            old_name='name',
            new_name='location_name',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='description',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='description',
            new_name='task_description',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='name',
            new_name='task_name',
        ),
        migrations.AlterField(
            model_name='equipments',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='backend.tasks'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='backend.projects'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='backend.projects'),
        ),
    ]
