# Generated by Django 4.2.3 on 2023-08-04 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_equipments_created_at_equipments_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='equipment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='backend.equipments'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_requirements', to='backend.locations'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_requirement', to='backend.tasks'),
        ),
        migrations.AlterField(
            model_name='taskperproject',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_task_project', to='backend.locations'),
        ),
        migrations.AlterField(
            model_name='taskperproject',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_per_project', to='backend.tasks'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_workers', to='backend.locations'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='backend.tasks'),
        ),
    ]
