# Generated by Django 4.2.3 on 2023-08-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_requirements_equipment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskperproject',
            name='project_id',
        ),
    ]
