# Generated by Django 4.2.3 on 2023-08-12 06:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_taskperproject_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='location_description',
            new_name='leader_name',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='equipment_id',
        ),
        migrations.RemoveField(
            model_name='taskperproject',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='days',
        ),
        migrations.AddField(
            model_name='locations',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='locations',
            name='project_category',
            field=models.TextField(default='Nyumba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locations',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='locations',
            name='supervisor',
            field=models.TextField(default='John'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirements',
            name='name',
            field=models.CharField(default='koleo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskperproject',
            name='name',
            field=models.CharField(default='excavation', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirements',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_requirement', to='backend.taskperproject'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='backend.taskperproject'),
        ),
    ]
