# Generated by Django 4.2.3 on 2023-08-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_location_description_locations_leader_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='last_name',
        ),
    ]
